export const Constants = {
    ENDPOINT_KEY: 'ENDPOINT_KEY',
    REQUEST: 'REQUEST',
    RESPONSE: 'RESPONSE',
    BODY: 'BODY',
    QUERY: 'QUERY',
    HEADERS: 'HEADERS',
    ROUTE_PARAM: 'ROUTE_PARAM',
    CONTROLLER_KEY: 'CONTROLLER_KEY',
    API_DOCS_KEY: 'API_DOCS_KEY',
};
